### PR TITLE
Upgrade to Angular11

### PR DESCRIPTION
**Pull request by jpalmowski**
- Codelyzer was manually bumped, all other changes to tsconfigs and angular.json were made by the cli
- All tests pass

### CODE REVIEW

**Comment by jpalmowski** [comment]
Hi, do you have any comments on this PR?  Have I missed anything?

**Comment by jpalmowski** [comment]
@HNeukermans  *bump*

**Comment by carol-braileanu** [comment]
Is anyone going to merge this? We need the Angular 11 version...

**Comment by MikeMatusz** [comment]
@HNeukermans @thduttonuk Any chance someone could take a look at this?  With Angular 12 just released, it would be nice to have this merged, since now we can look into transitioning to Ivy for publishing.

**Comment by JAspeling** [comment]
This feels like a dead repo :/

**Comment by afermon** [comment]
Will this version be published on npm @thduttonuk ?  

Thanks!

**Comment by JAspeling** [comment]
@thduttonuk Can this be released to npm please.

**Pull request merged**
