### PR TITLE
Update to Angular 12

### LINKED ISSUE #164: Angular 11
Thanks for this tool!

What's involved with updating this for Angular 11? (Bonus question: What's involved with getting this ivy-compatible?)

### LINKED ISSUE #174: Package "ng2-signalr" has an incompatible peer dependency to "@angular/common" while migrating to Angular 12
Package "ng2-signalr" has an incompatible peer dependency to "@angular/common" (requires "^10.0.0" (extended), would install "12.0.1").
                  Package "ng2-signalr" has an incompatible peer dependency to "@angular/core" (requires "^10.0.0" (extended), would install "12.0.1").
× Migration failed: Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.
  See "C:\Users\admin1\AppData\Local\Temp\ng-nQ21Q5\angular-errors.log" for further details.

### PR DESCRIPTION
**Pull request by leifjones**
1. Run `ng update @angular/core@12 @angular/cli@12 -C` per update guide: https://update.angular.io/?l=3&v=11.0-12.0
2. Increment version numbers
3. Run `npm audit fix` and the suggested command to deep-update ini

Fix #174
Fix #164

### CODE REVIEW

**Comment by leifjones** [comment]
This upgrade addresses a number of vulnerabilities, including 1 critical one.

**Comment by Bykiev** [comment]
@mrsegen, when it will be merged? I'm awaiting Angular 11 release

**Comment by leifjones** [comment]
@Bykiev it’s not my call. It’s for @HNeukermans (or another maintainer?) to approve and release (or for someone to put up and be ready to maintain a fork).

It wouldn’t be ideal, but if this meets your needs, you could fork this branch and publish to a local repo accessible to your build process.

**Comment by leifjones** [comment]
Thanks @thduttonuk!

In case this helps anyone: Someone reached out to me that this PR didn't work for them, but they were able to get the previously released version working via `npm install --force`

**Pull request merged**
