### PR TITLE
update to InjectableToken from OpaqueToken

### PR DESCRIPTION
**Pull request by pbriones**
-Update to ng5 compatibility
-Add //@ dynamic for static classes to enable compilation
-Convert Subject to Observables using subject.asObservable, where appropriate

### CODE REVIEW

**Comment by HNeukermans** [comment]
@pbriones ,

Awesome work.  Will merge it + publish asap

**Comment by cecotw** [comment]
`InjectionToken<any>`

**Comment by pbriones** [comment]
@cecotw, added the strong-typing for signalR token and verbose <any> for the other. The dependent functions weren't utilizing it so I didn't add it before, but you're right; better safe than sorry:)

**Comment by Fabf** [comment]
Would be great to have these upgrade soon :-) 👍

**Comment by thduttonuk** [comment]
When will these be published? Need to run in an Angular 5 project.

**Comment by dipanmehta** [comment]
@HNeukermans can we please have npm package compatible with angular 5 ? 
many thank
Dipan

**Comment by stevencohn** [comment]
As I mentioned in issue #92, this git repo has been updated to deal with OpaqueToken however it doesn't appear that this change has been published to npm yet. You can download this repo and build locally and install from the local dist folder. Or @HNeukermans could update npm! Please!?

**Comment by jorawarsingh** [comment]
H! @HNeukermans is it published with angular 5 support to npm?

**Comment by gabguy** [comment]
Please publish

**Pull request merged**
