### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by AbrarJahin**

### CODE REVIEW

**Comment by HNeukermans** [comment]
Hi @AbrarJahin,

thx for the pull request. But...
I think signalr needs to connect to the backend, not the frontend.

Agree?

**Comment by AbrarJahin** [comment]
Yes, it should connect with backend hub. 

But I am not sure that if there is any hub in previous url

**Comment by HNeukermans** [comment]
you can check with this url
http://ng2-signalr-backend.azurewebsites.net/signalr/hubs

**Comment by AbrarJahin** [comment]
Thanks.

I am closing this PR

**Pull request closed without merging**
